In [59]:
# !pip install nb_black

In [60]:
%load_ext lab_black

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [48]:
bankdata = pd.read_csv("./machine-learning-databases/bill_authentication.csv")

In [49]:
bankdata.shape

(1372, 5)

In [50]:
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [51]:
X = bankdata.drop("Class", axis=1)
y = bankdata["Class"]

In [52]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [53]:
from sklearn.svm import SVC

svclassifier = SVC(kernel="linear")
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [54]:
y_pred = svclassifier.predict(X_test)

In [55]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[140   1]
 [  2 132]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       141
           1       0.99      0.99      0.99       134

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



## Kernel SVM: Polynomial and Gaussian

In [56]:
# Assign colum names to the dataset
colnames = ["sepal-length", "sepal-width", "petal-length", "petal-width", "Class"]

# Read dataset to pandas dataframe
irisdata = pd.read_csv("./machine-learning-databases/iris.data", names=colnames)

X = irisdata.drop("Class", axis=1)
y = irisdata["Class"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


# polynomial
from sklearn.svm import SVC

svclassifier = SVC(kernel="poly", degree=8)
svclassifier.fit(X_train, y_train)

# gaussian
# from sklearn.svm import SVC
# svclassifier = SVC(kernel='rbf')
# svclassifier.fit(X_train, y_train)


y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

/Users/OptimusPrime/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[14  0  0]
 [ 0  6  0]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      1.00      1.00         6
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

